### ISSUE TITLE
Connection to server failed

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#172] opened 2017-11-23 09:49 UTC
#### :tophat: User Story

Connection to server failed message on trying to manage internal tools through control panel.

#### :clipboard: Related documentation
meta.decidim.barcelona
![captura de 2017-11-23 10-42-12](https://user-images.githubusercontent.com/27766903/33166809-e2721aaa-d03b-11e7-9dc3-09a486020fbb.png)
Click on NEW
![captura de 2017-11-23 10-42-23](https://user-images.githubusercontent.com/27766903/33166836-f6965be0-d03b-11e7-84e5-e489d02ebe6a.png)
decidim.coterrats.com
![captura de 2017-11-23 12-36-25](https://user-images.githubusercontent.com/27766903/33171063-1b45a3ec-d04b-11e7-916c-b88455892f8f.png)
Click on PROCESS NAME
![captura de 2017-11-23 12-36-53](https://user-images.githubusercontent.com/27766903/33171090-34bf8df6-d04b-11e7-8967-b8bec90b770f.png)

**Comment by mrcasals** [comment] 2017-11-24 11:19
Hi @josanFFiG!

Does this happen every time you access these places, or is it something that randomly occurs?

**Comment by josanFFiG** [comment] 2017-11-27 11:46
Just checked and same error message shown.

**Comment by josanFFiG** [comment] 2017-11-30 14:23
Hi again @mrcasals!
Could it be related to recent server migrations?
Another "case of use": We need to delete or unpublish urgently a process on coterrats.decidim.com
When we try to access to edition in order to delete it: same error is shown.
The process we are talking about is: https://decidim.coterrats.com/admin/participatory_processes/grades-obertes-201710/
It's shown on site through frontend and through backend (clicking eye icon), but it can't we edited.
This process was published before migration.
The one that was configured after migration is working properly.

**Comment by mrcasals** [comment] 2017-11-30 14:39
Hi @josanFFiG!

The first issue is solved by https://github.com/decidim/decidim/pull/2243, PR #175 updates decidim.barcelona to fix this error. Other instances already have this solved (those using version 0.7.4 or newer):

https://decidim-monitor.herokuapp.com

For the other issue I'll try to check what's going on.

**Comment by oriolgual** [comment] 2017-11-30 19:56
@mrcasals just FYI I've unpublished the process.

**Comment by oriolgual** [comment] 2018-01-26 08:45
I'm closing this, please @josanFFiG reopen if the issue is still happening.

**Closed by oriolgual** 2018-01-26 08:45 UTC
